#!/bin/bash

declare IS_BACKEND_FOLDER_CHANGE=$(git diff --staged --compact-summary | grep 'backend/')
echo "IS_BACKEND_FOLDER_CHANGE --> $IS_BACKEND_FOLDER_CHANGE"

if [[ $IS_BACKEND_FOLDER_CHANGE ]]; then
pushd backend
./gradlew diktatCheck
./gradlew detekt
popd
fi

declare IS_FRONTEND_FOLDER_CHANGE=$(git diff --staged --compact-summary | grep 'frontend/')
echo "IS_FRONTEND_FOLDER_CHANGE --> $IS_FRONTEND_FOLDER_CHANGE"

if [[ $IS_FRONTEND_FOLDER_CHANGE ]]; then
pushd frontend
yarn format:precommit
popd
fi