/*
 * This file is generated by jOOQ.
 */
package ch.learntrack.backend.persistence.tables.pojos


import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
public data class UserSchool(
    public val userId: UUID,
    public val schoolId: UUID
): Serializable {

    public override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserSchool = other as UserSchool
        if (this.userId != o.userId)
            return false
        if (this.schoolId != o.schoolId)
            return false
        return true
    }

    public override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.userId.hashCode()
        result = prime * result + this.schoolId.hashCode()
        return result
    }

    public override fun toString(): String {
        val sb = StringBuilder("UserSchool (")

        sb.append(userId)
        sb.append(", ").append(schoolId)

        sb.append(")")
        return sb.toString()
    }
}
