/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence.tables.references


import ch.learnup.backend.persistence.tables.TestTable



/**
 * The table <code>public.t_test</code>.
 */
val TEST: TestTable = TestTable.TEST
