/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence.tables.references


import ch.learnup.backend.persistence.tables.GradeTable
import ch.learnup.backend.persistence.tables.SchoolTable
import ch.learnup.backend.persistence.tables.SubjectTable
import ch.learnup.backend.persistence.tables.UserGradeTable
import ch.learnup.backend.persistence.tables.UserSchoolTable
import ch.learnup.backend.persistence.tables.UserTable



/**
 * The table <code>public.t_grade</code>.
 */
public val GRADE: GradeTable = GradeTable.GRADE

/**
 * The table <code>public.t_school</code>.
 */
public val SCHOOL: SchoolTable = SchoolTable.SCHOOL

/**
 * The table <code>public.t_subject</code>.
 */
public val SUBJECT: SubjectTable = SubjectTable.SUBJECT

/**
 * The table <code>public.t_user</code>.
 */
public val USER: UserTable = UserTable.USER

/**
 * The table <code>public.t_user_grade</code>.
 */
public val USER_GRADE: UserGradeTable = UserGradeTable.USER_GRADE

/**
 * The table <code>public.t_user_school</code>.
 */
public val USER_SCHOOL: UserSchoolTable = UserSchoolTable.USER_SCHOOL
