/*
 * This file is generated by jOOQ.
 */
package ch.learntrack.backend.persistence.tables


import ch.learntrack.backend.persistence.Public
import ch.learntrack.backend.persistence.keys.PK_SUBJECT
import ch.learntrack.backend.persistence.keys.T_SUBJECT__FK_SUBJECT_GRADE
import ch.learntrack.backend.persistence.keys.T_SUBJECT__FK_SUBJECT_USER
import ch.learntrack.backend.persistence.tables.GradeTable.TGradePath
import ch.learntrack.backend.persistence.tables.UserTable.TUserPath
import ch.learntrack.backend.persistence.tables.records.SubjectRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
public open class SubjectTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SubjectRecord>?,
    parentPath: InverseForeignKey<out Record, SubjectRecord>?,
    aliased: Table<SubjectRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SubjectRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    public companion object {

        /**
         * The reference instance of <code>public.t_subject</code>
         */
        public val SUBJECT: SubjectTable = SubjectTable()
    }

    /**
     * The class holding records for this type
     */
    public override fun getRecordType(): Class<SubjectRecord> = SubjectRecord::class.java

    /**
     * The column <code>public.t_subject.id</code>.
     */
    public val ID: TableField<SubjectRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.t_subject.name</code>.
     */
    public val NAME: TableField<SubjectRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.t_subject.grade_id</code>.
     */
    public val GRADE_ID: TableField<SubjectRecord, UUID?> = createField(DSL.name("grade_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.t_subject.created</code>.
     */
    public val CREATED: TableField<SubjectRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.t_subject.updated</code>.
     */
    public val UPDATED: TableField<SubjectRecord, LocalDateTime?> = createField(DSL.name("updated"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.t_subject.teacher_id</code>.
     */
    public val TEACHER_ID: TableField<SubjectRecord, UUID?> = createField(DSL.name("teacher_id"), SQLDataType.UUID, this, "")

    private constructor(alias: Name, aliased: Table<SubjectRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SubjectRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SubjectRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_subject</code> table reference
     */
    public constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_subject</code> table reference
     */
    public constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_subject</code> table reference
     */
    public constructor(): this(DSL.name("t_subject"), null)

    public constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SubjectRecord>?, parentPath: InverseForeignKey<out Record, SubjectRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, SUBJECT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public open class TSubjectPath : SubjectTable, Path<SubjectRecord> {
        public constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SubjectRecord>?, parentPath: InverseForeignKey<out Record, SubjectRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<SubjectRecord>): super(alias, aliased)
        public override fun `as`(alias: String): TSubjectPath = TSubjectPath(DSL.name(alias), this)
        public override fun `as`(alias: Name): TSubjectPath = TSubjectPath(alias, this)
        public override fun `as`(alias: Table<*>): TSubjectPath = TSubjectPath(alias.qualifiedName, this)
    }
    public override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    public override fun getPrimaryKey(): UniqueKey<SubjectRecord> = PK_SUBJECT
    public override fun getReferences(): List<ForeignKey<SubjectRecord, *>> = listOf(T_SUBJECT__FK_SUBJECT_GRADE, T_SUBJECT__FK_SUBJECT_USER)

    private lateinit var _tGrade: TGradePath

    /**
     * Get the implicit join path to the <code>public.t_grade</code> table.
     */
    public fun tGrade(): TGradePath {
        if (!this::_tGrade.isInitialized)
            _tGrade = TGradePath(this, T_SUBJECT__FK_SUBJECT_GRADE, null)

        return _tGrade;
    }

    public val tGrade: TGradePath
        get(): TGradePath = tGrade()

    private lateinit var _tUser: TUserPath

    /**
     * Get the implicit join path to the <code>public.t_user</code> table.
     */
    public fun tUser(): TUserPath {
        if (!this::_tUser.isInitialized)
            _tUser = TUserPath(this, T_SUBJECT__FK_SUBJECT_USER, null)

        return _tUser;
    }

    public val tUser: TUserPath
        get(): TUserPath = tUser()
    public override fun `as`(alias: String): SubjectTable = SubjectTable(DSL.name(alias), this)
    public override fun `as`(alias: Name): SubjectTable = SubjectTable(alias, this)
    public override fun `as`(alias: Table<*>): SubjectTable = SubjectTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    public override fun rename(name: String): SubjectTable = SubjectTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    public override fun rename(name: Name): SubjectTable = SubjectTable(name, null)

    /**
     * Rename this table
     */
    public override fun rename(name: Table<*>): SubjectTable = SubjectTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    public override fun where(condition: Condition): SubjectTable = SubjectTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    public override fun where(conditions: Collection<Condition>): SubjectTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    public override fun where(vararg conditions: Condition): SubjectTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    public override fun where(condition: Field<Boolean?>): SubjectTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL public override fun where(condition: SQL): SubjectTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL public override fun where(@Stringly.SQL condition: String): SubjectTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL public override fun where(@Stringly.SQL condition: String, vararg binds: Any?): SubjectTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL public override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): SubjectTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    public override fun whereExists(select: Select<*>): SubjectTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    public override fun whereNotExists(select: Select<*>): SubjectTable = where(DSL.notExists(select))
}
