/*
 * This file is generated by jOOQ.
 */
package ch.learntrack.backend.persistence.tables


import ch.learntrack.backend.persistence.Public
import ch.learntrack.backend.persistence.keys.PK_USER_GRADE
import ch.learntrack.backend.persistence.keys.T_USER_GRADE__FK_USER_GRADE_GRADE
import ch.learntrack.backend.persistence.keys.T_USER_GRADE__FK_USER_GRADE_USER
import ch.learntrack.backend.persistence.tables.GradeTable.TGradePath
import ch.learntrack.backend.persistence.tables.UserTable.TUserPath
import ch.learntrack.backend.persistence.tables.records.UserGradeRecord

import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
public open class UserGradeTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserGradeRecord>?,
    parentPath: InverseForeignKey<out Record, UserGradeRecord>?,
    aliased: Table<UserGradeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserGradeRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    public companion object {

        /**
         * The reference instance of <code>public.t_user_grade</code>
         */
        public val USER_GRADE: UserGradeTable = UserGradeTable()
    }

    /**
     * The class holding records for this type
     */
    public override fun getRecordType(): Class<UserGradeRecord> = UserGradeRecord::class.java

    /**
     * The column <code>public.t_user_grade.user_id</code>.
     */
    public val USER_ID: TableField<UserGradeRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.t_user_grade.grade_id</code>.
     */
    public val GRADE_ID: TableField<UserGradeRecord, UUID?> = createField(DSL.name("grade_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserGradeRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserGradeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserGradeRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_user_grade</code> table reference
     */
    public constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_user_grade</code> table reference
     */
    public constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_user_grade</code> table reference
     */
    public constructor(): this(DSL.name("t_user_grade"), null)

    public constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserGradeRecord>?, parentPath: InverseForeignKey<out Record, UserGradeRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USER_GRADE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public open class TUserGradePath : UserGradeTable, Path<UserGradeRecord> {
        public constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserGradeRecord>?, parentPath: InverseForeignKey<out Record, UserGradeRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UserGradeRecord>): super(alias, aliased)
        public override fun `as`(alias: String): TUserGradePath = TUserGradePath(DSL.name(alias), this)
        public override fun `as`(alias: Name): TUserGradePath = TUserGradePath(alias, this)
        public override fun `as`(alias: Table<*>): TUserGradePath = TUserGradePath(alias.qualifiedName, this)
    }
    public override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    public override fun getPrimaryKey(): UniqueKey<UserGradeRecord> = PK_USER_GRADE
    public override fun getReferences(): List<ForeignKey<UserGradeRecord, *>> = listOf(T_USER_GRADE__FK_USER_GRADE_USER, T_USER_GRADE__FK_USER_GRADE_GRADE)

    private lateinit var _tUser: TUserPath

    /**
     * Get the implicit join path to the <code>public.t_user</code> table.
     */
    public fun tUser(): TUserPath {
        if (!this::_tUser.isInitialized)
            _tUser = TUserPath(this, T_USER_GRADE__FK_USER_GRADE_USER, null)

        return _tUser;
    }

    public val tUser: TUserPath
        get(): TUserPath = tUser()

    private lateinit var _tGrade: TGradePath

    /**
     * Get the implicit join path to the <code>public.t_grade</code> table.
     */
    public fun tGrade(): TGradePath {
        if (!this::_tGrade.isInitialized)
            _tGrade = TGradePath(this, T_USER_GRADE__FK_USER_GRADE_GRADE, null)

        return _tGrade;
    }

    public val tGrade: TGradePath
        get(): TGradePath = tGrade()
    public override fun `as`(alias: String): UserGradeTable = UserGradeTable(DSL.name(alias), this)
    public override fun `as`(alias: Name): UserGradeTable = UserGradeTable(alias, this)
    public override fun `as`(alias: Table<*>): UserGradeTable = UserGradeTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    public override fun rename(name: String): UserGradeTable = UserGradeTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    public override fun rename(name: Name): UserGradeTable = UserGradeTable(name, null)

    /**
     * Rename this table
     */
    public override fun rename(name: Table<*>): UserGradeTable = UserGradeTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    public override fun where(condition: Condition): UserGradeTable = UserGradeTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    public override fun where(conditions: Collection<Condition>): UserGradeTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    public override fun where(vararg conditions: Condition): UserGradeTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    public override fun where(condition: Field<Boolean?>): UserGradeTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL public override fun where(condition: SQL): UserGradeTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL public override fun where(@Stringly.SQL condition: String): UserGradeTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL public override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserGradeTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL public override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserGradeTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    public override fun whereExists(select: Select<*>): UserGradeTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    public override fun whereNotExists(select: Select<*>): UserGradeTable = where(DSL.notExists(select))
}
