/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence


import ch.learnup.backend.persistence.tables.TestTable

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class LearnupBackend : SchemaImpl("learnup_backend", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>learnup_backend</code>
         */
        val LEARNUP_BACKEND: LearnupBackend = LearnupBackend()
    }

    /**
     * The table <code>learnup_backend.t_test</code>.
     */
    val TEST: TestTable get() = TestTable.TEST

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        TestTable.TEST
    )
}
