/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence.tables.records


import ch.learnup.backend.persistence.tables.GradeTable
import ch.learnup.backend.persistence.tables.pojos.Grade

import java.time.LocalDateTime
import java.util.UUID

import org.jetbrains.annotations.NotNull
import org.jetbrains.annotations.Nullable
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
public open class GradeRecord private constructor() : UpdatableRecordImpl<GradeRecord>(GradeTable.GRADE) {

    public open var id: UUID
        set(value): Unit = set(0, value)
    @NotNull
        get(): UUID = get(0) as UUID

    public open var name: String
        set(value): Unit = set(1, value)
    @NotNull
        get(): String = get(1) as String

    public open var schoolId: UUID
        set(value): Unit = set(2, value)
    @NotNull
        get(): UUID = get(2) as UUID

    public open var created: LocalDateTime?
        set(value): Unit = set(3, value)
    @Nullable
        get(): LocalDateTime? = get(3) as LocalDateTime?

    public open var updated: LocalDateTime?
        set(value): Unit = set(4, value)
    @Nullable
        get(): LocalDateTime? = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    public override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised GradeRecord
     */
    public constructor(id: UUID, name: String, schoolId: UUID, created: LocalDateTime? = null, updated: LocalDateTime? = null): this() {
        this.id = id
        this.name = name
        this.schoolId = schoolId
        this.created = created
        this.updated = updated
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised GradeRecord
     */
    public constructor(value: Grade?): this() {
        if (value != null) {
            this.id = value.id
            this.name = value.name
            this.schoolId = value.schoolId
            this.created = value.created
            this.updated = value.updated
            resetChangedOnNotNull()
        }
    }
}
