/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence.tables.records


import ch.learnup.backend.persistence.tables.UserSchoolTable
import ch.learnup.backend.persistence.tables.pojos.UserSchool

import java.util.UUID

import org.jetbrains.annotations.NotNull
import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
public open class UserSchoolRecord private constructor() : UpdatableRecordImpl<UserSchoolRecord>(UserSchoolTable.USER_SCHOOL) {

    public open var userId: UUID
        set(value): Unit = set(0, value)
    @NotNull
        get(): UUID = get(0) as UUID

    public open var schoolId: UUID
        set(value): Unit = set(1, value)
    @NotNull
        get(): UUID = get(1) as UUID

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    public override fun key(): Record2<UUID?, UUID?> = super.key() as Record2<UUID?, UUID?>

    /**
     * Create a detached, initialised UserSchoolRecord
     */
    public constructor(userId: UUID, schoolId: UUID): this() {
        this.userId = userId
        this.schoolId = schoolId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised UserSchoolRecord
     */
    public constructor(value: UserSchool?): this() {
        if (value != null) {
            this.userId = value.userId
            this.schoolId = value.schoolId
            resetChangedOnNotNull()
        }
    }
}
