/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence.tables.daos


import ch.learnup.backend.persistence.UserRole
import ch.learnup.backend.persistence.tables.UserTable
import ch.learnup.backend.persistence.tables.pojos.User
import ch.learnup.backend.persistence.tables.records.UserRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl
import org.jooq.impl.EnumConverter


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserDao(configuration: Configuration?) : DAOImpl<UserRecord, User, UUID>(UserTable.USER, User::class.java, configuration) {

    /**
     * Create a new UserDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: User): UUID = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: UUID, upperInclusive: UUID): List<User> = fetchRange(UserTable.USER.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: UUID): List<User> = fetch(UserTable.USER.ID, *values)

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: UUID): User? = fetchOne(UserTable.USER.ID, value)

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfFirstName(lowerInclusive: String, upperInclusive: String): List<User> = fetchRange(UserTable.USER.FIRST_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    fun fetchByFirstName(vararg values: String): List<User> = fetch(UserTable.USER.FIRST_NAME, *values)

    /**
     * Fetch records that have <code>middle_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfMiddleName(lowerInclusive: String?, upperInclusive: String?): List<User> = fetchRange(UserTable.USER.MIDDLE_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>middle_name IN (values)</code>
     */
    fun fetchByMiddleName(vararg values: String): List<User> = fetch(UserTable.USER.MIDDLE_NAME, *values)

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLastName(lowerInclusive: String, upperInclusive: String): List<User> = fetchRange(UserTable.USER.LAST_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    fun fetchByLastName(vararg values: String): List<User> = fetch(UserTable.USER.LAST_NAME, *values)

    /**
     * Fetch records that have <code>e_mail BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfEMail(lowerInclusive: String, upperInclusive: String): List<User> = fetchRange(UserTable.USER.E_MAIL, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>e_mail IN (values)</code>
     */
    fun fetchByEMail(vararg values: String): List<User> = fetch(UserTable.USER.E_MAIL, *values)

    /**
     * Fetch records that have <code>password BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfPassword(lowerInclusive: String, upperInclusive: String): List<User> = fetchRange(UserTable.USER.PASSWORD, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    fun fetchByPassword(vararg values: String): List<User> = fetch(UserTable.USER.PASSWORD, *values)

    /**
     * Fetch records that have <code>user_role BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUserRole(lowerInclusive: UserRole, upperInclusive: UserRole): List<User> = fetchRange(UserTable.USER.USER_ROLE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>user_role IN (values)</code>
     */
    fun fetchByUserRole(vararg values: UserRole): List<User> = fetch(UserTable.USER.USER_ROLE, *values)

    /**
     * Fetch records that have <code>birthdate BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfBirthdate(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<User> = fetchRange(UserTable.USER.BIRTHDATE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>birthdate IN (values)</code>
     */
    fun fetchByBirthdate(vararg values: LocalDateTime): List<User> = fetch(UserTable.USER.BIRTHDATE, *values)

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<User> = fetchRange(UserTable.USER.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<User> = fetch(UserTable.USER.CREATED, *values)

    /**
     * Fetch records that have <code>updated BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUpdated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<User> = fetchRange(UserTable.USER.UPDATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    fun fetchByUpdated(vararg values: LocalDateTime): List<User> = fetch(UserTable.USER.UPDATED, *values)
}
