/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence.tables


import ch.learnup.backend.persistence.Public
import ch.learnup.backend.persistence.keys.PK_USER_SCHOOL
import ch.learnup.backend.persistence.keys.T_USER_SCHOOL__FK_USER_SCHOOL_SCHOOL
import ch.learnup.backend.persistence.keys.T_USER_SCHOOL__FK_USER_SCHOOL_USER
import ch.learnup.backend.persistence.tables.SchoolTable.TSchoolPath
import ch.learnup.backend.persistence.tables.UserTable.TUserPath
import ch.learnup.backend.persistence.tables.records.UserSchoolRecord

import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserSchoolTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserSchoolRecord>?,
    parentPath: InverseForeignKey<out Record, UserSchoolRecord>?,
    aliased: Table<UserSchoolRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserSchoolRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_user_school</code>
         */
        val USER_SCHOOL: UserSchoolTable = UserSchoolTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserSchoolRecord> = UserSchoolRecord::class.java

    /**
     * The column <code>public.t_user_school.user_id</code>.
     */
    val USER_ID: TableField<UserSchoolRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.t_user_school.school_id</code>.
     */
    val SCHOOL_ID: TableField<UserSchoolRecord, UUID?> = createField(DSL.name("school_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserSchoolRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserSchoolRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserSchoolRecord>?, where: Condition): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_user_school</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_user_school</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_user_school</code> table reference
     */
    constructor(): this(DSL.name("t_user_school"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserSchoolRecord>?, parentPath: InverseForeignKey<out Record, UserSchoolRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USER_SCHOOL, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TUserSchoolPath : UserSchoolTable, Path<UserSchoolRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserSchoolRecord>?, parentPath: InverseForeignKey<out Record, UserSchoolRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UserSchoolRecord>): super(alias, aliased)
        override fun `as`(alias: String): TUserSchoolPath = TUserSchoolPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TUserSchoolPath = TUserSchoolPath(alias, this)
        override fun `as`(alias: Table<*>): TUserSchoolPath = TUserSchoolPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<UserSchoolRecord> = PK_USER_SCHOOL
    override fun getReferences(): List<ForeignKey<UserSchoolRecord, *>> = listOf(T_USER_SCHOOL__FK_USER_SCHOOL_USER, T_USER_SCHOOL__FK_USER_SCHOOL_SCHOOL)

    private lateinit var _tUser: TUserPath

    /**
     * Get the implicit join path to the <code>public.t_user</code> table.
     */
    fun tUser(): TUserPath {
        if (!this::_tUser.isInitialized)
            _tUser = TUserPath(this, T_USER_SCHOOL__FK_USER_SCHOOL_USER, null)

        return _tUser;
    }

    val tUser: TUserPath
        get(): TUserPath = tUser()

    private lateinit var _tSchool: TSchoolPath

    /**
     * Get the implicit join path to the <code>public.t_school</code> table.
     */
    fun tSchool(): TSchoolPath {
        if (!this::_tSchool.isInitialized)
            _tSchool = TSchoolPath(this, T_USER_SCHOOL__FK_USER_SCHOOL_SCHOOL, null)

        return _tSchool;
    }

    val tSchool: TSchoolPath
        get(): TSchoolPath = tSchool()
    override fun `as`(alias: String): UserSchoolTable = UserSchoolTable(DSL.name(alias), this)
    override fun `as`(alias: Name): UserSchoolTable = UserSchoolTable(alias, this)
    override fun `as`(alias: Table<*>): UserSchoolTable = UserSchoolTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserSchoolTable = UserSchoolTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserSchoolTable = UserSchoolTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserSchoolTable = UserSchoolTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition): UserSchoolTable = UserSchoolTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UserSchoolTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition): UserSchoolTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>): UserSchoolTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UserSchoolTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UserSchoolTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserSchoolTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserSchoolTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UserSchoolTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UserSchoolTable = where(DSL.notExists(select))
}
