/*
 * This file is generated by jOOQ.
 */
package ch.learntrack.backend.persistence.tables.daos


import ch.learntrack.backend.persistence.tables.SubjectTable
import ch.learntrack.backend.persistence.tables.pojos.Subject
import ch.learntrack.backend.persistence.tables.records.SubjectRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
public open class SubjectDao(configuration: Configuration?) : DAOImpl<SubjectRecord, Subject, UUID>(SubjectTable.SUBJECT, Subject::class.java, configuration) {

    /**
     * Create a new SubjectDao without any configuration
     */
    public constructor(): this(null)

    public override fun getId(o: Subject): UUID = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public fun fetchRangeOfId(lowerInclusive: UUID, upperInclusive: UUID): List<Subject> = fetchRange(SubjectTable.SUBJECT.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public fun fetchById(vararg values: UUID): List<Subject> = fetch(SubjectTable.SUBJECT.ID, *values)

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fun fetchOneById(value: UUID): Subject? = fetchOne(SubjectTable.SUBJECT.ID, value)

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public fun fetchRangeOfName(lowerInclusive: String, upperInclusive: String): List<Subject> = fetchRange(SubjectTable.SUBJECT.NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public fun fetchByName(vararg values: String): List<Subject> = fetch(SubjectTable.SUBJECT.NAME, *values)

    /**
     * Fetch records that have <code>grade_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public fun fetchRangeOfGradeId(lowerInclusive: UUID, upperInclusive: UUID): List<Subject> = fetchRange(SubjectTable.SUBJECT.GRADE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>grade_id IN (values)</code>
     */
    public fun fetchByGradeId(vararg values: UUID): List<Subject> = fetch(SubjectTable.SUBJECT.GRADE_ID, *values)

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<Subject> = fetchRange(SubjectTable.SUBJECT.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public fun fetchByCreated(vararg values: LocalDateTime): List<Subject> = fetch(SubjectTable.SUBJECT.CREATED, *values)

    /**
     * Fetch records that have <code>updated BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public fun fetchRangeOfUpdated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<Subject> = fetchRange(SubjectTable.SUBJECT.UPDATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    public fun fetchByUpdated(vararg values: LocalDateTime): List<Subject> = fetch(SubjectTable.SUBJECT.UPDATED, *values)

    /**
     * Fetch records that have <code>teacher_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public fun fetchRangeOfTeacherId(lowerInclusive: UUID?, upperInclusive: UUID?): List<Subject> = fetchRange(SubjectTable.SUBJECT.TEACHER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>teacher_id IN (values)</code>
     */
    public fun fetchByTeacherId(vararg values: UUID): List<Subject> = fetch(SubjectTable.SUBJECT.TEACHER_ID, *values)
}
