/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence.tables.pojos


import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Test(
    val id: UUID,
    val test: String? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Test = other as Test
        if (this.id != o.id)
            return false
        if (this.test == null) {
            if (o.test != null)
                return false
        }
        else if (this.test != o.test)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + (if (this.test == null) 0 else this.test.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Test (")

        sb.append(id)
        sb.append(", ").append(test)

        sb.append(")")
        return sb.toString()
    }
}
