/*
 * This file is generated by jOOQ.
 */
package ch.learnup.backend.persistence.tables.pojos


import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
public data class UserGrade(
    public val userId: UUID,
    public val gradeId: UUID
): Serializable {

    public override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserGrade = other as UserGrade
        if (this.userId != o.userId)
            return false
        if (this.gradeId != o.gradeId)
            return false
        return true
    }

    public override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.userId.hashCode()
        result = prime * result + this.gradeId.hashCode()
        return result
    }

    public override fun toString(): String {
        val sb = StringBuilder("UserGrade (")

        sb.append(userId)
        sb.append(", ").append(gradeId)

        sb.append(")")
        return sb.toString()
    }
}
